# main menu navigation url and icon
# 配置菜单导航的名称、路径和图标icon.
menu:
  Index:
    url: /
    icon: fa-home
  Tags:
    url: /tags
    icon: fa-tags
  Categories:
    url: /categories
    icon: fa-bookmark
  Archives:
    url: /archives
    icon: fa-archive
  About:
    url: /about
    icon: fa-user-circle-o
  Friends:
    url: /friends
    icon: fa-address-book

# Index cover carousel configuration.
# 首页封面轮播图的相关配置.
cover:
  showPrevNext: true # 是否显示左右切换按钮. Whether to display the left and right toggle buttons.
  showIndicators: true # 是否显示指示器. # Whether to display the indicators
  autoLoop: true # 是否自动轮播. Whether it is automatically rotated.
  duration: 120 # 切换延迟时间. Switching delay time.
  intervalTime: 5000 # 自动切换下一张的间隔时间. Automatically switch the interval of the next one.

# index page dream text,
# 配置首页显示"梦想"的语句.
dream:
  enable: true
  showTitle: true
  title: Motto
  text: 当你真正接受一个事物时，那她就是这个世界上最美好的东西。

# Whether to display the musics.
# 是否在首页显示音乐.
# 不再使用，使用了根目录下的aplayer
# music:
#   enable: true
#   showTitle: false
#   title: 听听音乐
#   fixed: true # 开启吸底模式
#   autoplay: true # 是否自动播放
#   theme: 'rgba(0,0,0,0)'
#   loop: 'all' # 音频循环播放, 可选值: 'all', 'one', 'none'
#   order: 'list' # 音频循环顺序, 可选值: 'list', 'random'
#   preload: 'auto' # 预加载，可选值: 'none', 'metadata', 'auto'
#   volume: 0.7 # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
#   listFolded: false # 列表默认折叠
#   listMaxHeight: #列表最大高度

music:
  enable: true
  # 所有页面中配置，每篇文章单独配置的可参考hexo-tag-aplayer的写法
  # {% meting "7158943707" "tencent" "playlist" "mini" "loop:all" "order:random" "volume:0.6" "lrctype:0"  "listfolded" "storagename:metingjs" "autoplay" "listmaxheight:340px" "preload:none" "theme:#ad7a86" %}
  id: '7158943707' #必须值	歌曲 id / 播放列表 id / 相册 id / 搜索关键字
  server:	'tencent' #必须值	音乐平台: netease, tencent, kugou, xiami, baidu
  type:	'playlist' #必须值	song, playlist, album, search, artist
  fixed: true #false	开启固定模式
  mini: true	#false	开启迷你模式
  loop: 'all'	#all	列表循环模式：all, one,none
  order: 'list'	#list	列表播放模式： list, random
  volume: 0.7	#0.7	播放器音量
  lrctype: 0	#0	歌词格式类型
  listfolded: true	#false	指定音乐播放列表是否折叠
  storagename: 'metingjs'	#metingjs	LocalStorage 中存储播放器设定的键名
  autoplay: false	#true	自动播放，移动端浏览器暂时不支持此功能
  mutex: true	#true	该选项开启时，如果同页面有其他 aplayer 播放，该播放器会暂停
  listmaxheight: '340px'	#340px	播放列表的最大长度
  preload: 'auto'	#auto	音乐文件预载入模式，可选项： none, metadata, auto
  theme: '#ad7a86'	#ad7a86	播放器风格色彩设置

# Whether to display the videos.
# 是否在首页显示视频.
# {% dplayer "url=http://oss.willhappy.cn/video/%E8%88%9E%E8%80%85.mp4" "addition=https://dplayer.daoapp.io/bilibili?aid=4157142" "api=https://api.prprpr.me/dplayer/" "pic=https://moeplayer.b0.upaiyun.com/dplayer/hikarunara.jpg" "id=9E2E3368B56CDBB4" "loop=yes" "theme=#FADFA3" "autoplay=false" "token=tokendemo" %}
dplayer:
  enable: true
  showTitle: true
  title: 视频剪辑
  height: # 如：400
  live: false #false 开启直播模式
  screenshot: true #false 开启截图，如果开启，视频和视频封面需要允许跨域
  hotkey:  #true 开启热键，支持快进、快退、音量控制、播放暂停
  autoplay: false #false 是否自动播放
  theme: '#42b983'
  loop: false #false 是否循环播放
  preload: 'auto' #'auto' 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7 #0.7 音量
  mutex: #互斥，阻止多个播放器同时播放，当前播放器播放时暂停其他播放器
  video:
    url: 'http://oss.willhappy.cn/video/%E8%88%9E%E6%9E%97.mp4' #视频链接
    type: 'auto' #可选值: 'auto', 'hls', 'flv', 'dash', 'webtorrent', 'normal' 或其他自定义类型
    pic: #视频封面
    quality: #清晰度
    defaultQuality: #默认清晰度
    thumbnails: #视频缩略图，可以使用 DPlayer-thumbnails 生成
    customType: #自定义类型
  subtitle:
    url: #required 字幕链接
    type: #'webvtt'	字幕类型，可选值: 'webvtt', 'ass'，目前只支持 webvtt
    fontSize: #'20px'	字幕字号
    bottom: #'40px'	字幕距离播放器底部的距离，取值形如: '10px' '10%'
    color: #'#fff'	字幕颜色
  danmaku:
    id: '9E2E3368B56CDBB4' #required	弹幕池id，必须唯一
    api: 'https://api.prprpr.me/dplayer/' #required	见#弹幕接口
    token: 'tokendemo' #弹幕后端验证 token
    maximum: 1000 #弹幕最大数量
    addition: 'https://api.prprpr.me/dplayer/v3/bilibili?aid=4157142' #额外外挂弹幕，见#bilibili 弹幕
    user: 'DIYgod' #'DIYgod'	弹幕用户名
    bottom: '15%' #弹幕距离播放器底部的距离，防止遮挡字幕，取值形如: '10px' '10%'
    unlimited: true #海量弹幕模式，即使重叠也展示全部弹幕，请注意播放器会记忆用户设置，用户手动设置后即失效
  
  

# Whether to display the title of the recommended posts
# 是否显示推荐文章的标题
recommend:
  showTitle: true

# Configure website favicon and LOGO
# 配置网站favicon和网站LOGO
favicon: http://oss.willhappy.cn/private/pic-%E5%A4%B4%E5%83%8F4-%E9%80%8F%E6%98%8E.png
logo: http://oss.willhappy.cn/private/pic-%E5%A4%B4%E5%83%8F4-%E9%80%8F%E6%98%8E.png

# The configuration of the second button in the home banner,
# including the display name of the button, the font awesome icon, and the hyperlink to the button.
# 首页 banner 中的第二个按钮的配置，包括按钮的显示名称、font awesome图标和按钮的超链接.
indexbtn:
  enable: true
  name: Github
  icon: fa-github-alt
  url: https://github.com/williamHappy/williamHappy.github.io

# The configurations of the second line of home banner
# icon/button will not show up if you leave the corresponding socialLink empty
# 首页 banner 中的第二行个人信息配置，留空即不启用
socialLink:
  home: 
  qq: 583876674
  github: https://github.com/williamHappy
  email: ctwang1994@163.com
  wechat: http://oss.willhappy.cn/private/wechat_url.jpg
  weibo: https://weibo.com/williamhappy

# Whether to activate the Post TOC, and Configure which title types are supported by TOC support.
# You can add `toc: false` to the Front-matter of a post to turn off the TOC.
# 是否激活文章 TOC 功能，并配置TOC支持选中哪些标题类型，这是全局配置。
# 可以在某篇文章的 Front-matter 中再加上`toc: false`，使该篇文章关闭TOC目录功能
toc:
  enable: true
  heading: h2, h3, h4
  showToggleBtn: true # 是否显示切换TOC目录展开收缩的按钮

# Whether the code is broken.
# 代码是否折行
code:
  break: true

# 是否激活文章末尾的打赏功能，默认激活（你替换为的你自己的微信、支付宝二维码图片、或者使用网络图片也可以）.
reward:
  enable: true
  title: 你的赏识是我前进的动力
  wechat: http://oss.willhappy.cn/private/wechat_code_me.png
  alipay: http://oss.willhappy.cn/private/alipay_code_me.png

# Whether to activate the copyright information of the blog and author when copying the post content.
# minCharNumber: Approve copyright information by copying at least how many characters.
# 是否激活复制文章时追加博客和作者的版权信息.
copyright:
  enable: true
  minCharNumber: 120 # 至少复制多少个字符就追加版权信息.
  description: 本文章著作权归作者所有，任何形式的转载都请注明出处。

# Whether to activate the mathjax, this is a global configuration, but the post still does not open the mathjax rendering.
# Considering that the mathjax loading is time consuming,
# you also need to add `mathjax: true` to the Front-matter of the post that needs to be rendered.
# 是否激活mathjax数学公式，这是全局配置，但文章仍然不会都开启mathjax渲染，
# 考虑到mathjax加载比较耗时，你还需要在需要渲染的文章的Front-matter中再加上`mathjax: true`才行.
mathjax:
  enable: true
  cdn: https://cdn.bootcss.com/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Post word count, reading duration, site total word count.
# Before you activate, please confirm that you have installed the hexo-wordcount plugin,
# install the plugin command: `npm i --save hexo-wordcount`.
# 文章字数统计、阅读时长、总字数统计
# 激活前请确认你已经安装了 hexo-wordcount 插件，安装命令: `npm i --save hexo-wordcount`
wordCount:
  enable: true
  postWordCount: true
  min2read: true
  totalCount: true

# Whether to activate the 'love' effect of clicking on the page.
# 是否激活点击页面的'爱心'效果，默认激活.
clicklove:
  enable: true

# profile in about page, including avatars, career, and personal introductions.
# 在”关于”页面中配置个人信息，包括头像、职业和个人介绍.
profile:
  avatar: http://oss.willhappy.cn/private/pic-%E5%A4%B4%E5%83%8F4-%E9%80%8F%E6%98%8E.png
  career: Free Experientialism Person / Software Engineer
  introduction: Early in the day it was whispered that we should sail in a boat, only thou and I, and never a soul in the world would know of this our pilgrimage to no country and to no end.     在清晓的密语中，我们约定了同去泛舟，世界上没有一个人知道我们这无目的无终止的遨游。

# config my projects informations in about page.
# If you don't want to display this `My Projects` content, you can deactivate or delete this configuration.
# 在“关于”页面配置"我的项目"信息，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
myProjects:
  enable: true
  data:
    willhappy:
      icon: fa-home
      iconBackground: 'linear-gradient(to bottom right, #66BB6A 0%, #81C784 100%)'
      url: williamHappy.github.io
      desc: This is my Hexo blog system.
    whome-service:
        icon: fa-server
        iconBackground: 'linear-gradient(to bottom right, #F06292 0%, #EF5350 100%)'
        url: https://github.com/williamHappy/whome-service
        desc: This is my complex distributed project.
    universe_project:
        icon: fa-tv
        iconBackground: 'linear-gradient(to bottom right, #29B6F6 0%, #1E88E5 100%)'
        url: https://github.com/williamHappy/universe_project
        desc: Knowledge one of my more beautiful homepage system.

# config my skills informations in about page.
# If you don't want to display this `My Skills` content, you can deactivate or delete this configuration.
# 在“关于”页面配置"我的技能"信息，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
mySkills:
  enable: true
  data:
    Java:
      background: 'linear-gradient(to right, #FF0066 0%, #FF00CC 100%)'
      percent: 85%
    JavaScript:
      background: 'linear-gradient(to right, #9900FF 0%, #CC66FF 100%)'
      percent: 60%
    VUEJS:
      background: 'linear-gradient(to right, #2196F3 0%, #42A5F5 100%)'
      percent: 75%
    MYSQL:
      background: 'linear-gradient(to right, #4CAF50 0%, #81C784 100%)'
      percent: 75%
    Python:
      background: 'linear-gradient(to right, #00BCD4 0%, #80DEEA 100%)'
      percent: 20%
    程序设计:
      background: 'linear-gradient(to right, #FFEB3B 0%, #FFF176 100%)'
      percent: 75%

# config gallery of my photos in about page.
# If you don't want to display this `Gallery` content, you can deactivate or delete this configuration.
# 在“关于”页面配置"我的相册"图片，如果你不需要这些信息则可以将其设置为不激活或者将其删除.
myGallery:
  enable: true
  data:
    - /medias/featureimages/0.jpg
    - /medias/featureimages/1.jpg
    - /medias/featureimages/2.jpg

# Whether to display post-calender in the `archive` page
# 设置在归档页面中是否显示'文章日历'控件
postCalendar: true

# the Gitalk config，default disabled
# Gitalk 评论模块的配置，默认为不激活
gitalk:
  enable: true
  owner: williamHappy
  repo: williamHappy.github.io
  oauth:
    clientId: c012900cfa3718580687
    clientSecret: 15fb2a23c381c0bbc4d720ee609ee07a57c24b7a
  admin: williamHappy

# the Gitment config，default disabled
# Gitment 评论模块的配置，默认为不激活
gitment:
  enable: false
  owner:
  repo:
  oauth:
    clientId:
    clientSecret:

# disqus config, default disabled
# Disqus评论模块的配置，默认为不激活
disqus:
  enable: false
  shortname:

# Livere comment configuration, the default is not activated
# Livere 来必力评论模块的配置，默认为不激活
livere:
  enable: false
  uid:

# The configuration of the Valine comment module is not activated by default.
# To use it, activate the configuration item and set appId and appKey.
# Valine 评论模块的配置，默认为不激活，如要使用，就请激活该配置项，并设置 appId 和 appKey.
valine:
  enable: false
  appId:
  appKey:
  notify: false
  verify: false
  visitor: true
  avatar: 'mm' # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  pageSize: 10
  placeholder: 'just go go' # Comment Box placeholder

# Whether to display fork me on github icon and link, default true, You can change it to your repo address
# 配置是否在 header 中显示 fork me on github 的图标，默认为true，你可以修改为你的仓库地址.
githubLink:
  enable: true
  url: https://github.com/williamHappy/williamHappy.github.io
  title: Fork Me

# The password verification feature of read post. To use this feature,
# activate the configuration item and write the 'password' key and Cipher in the post's Front-matter.
# Note: In order to ensure that the original password will not be leaked to the web page,
# the password of the article must be encrypted by 'SHA256' so that it will not be cracked.
# 阅读文章的密码验证功能，如要使用此功能请激活该配置项，并在对应文章的Front-matter中写上'password'的键和加密后的密文即可.
# 请注意：为了保证密码原文不会被泄露到网页中，文章的密码必须是通过'SHA256'加密的，这样就不会被破解.
verifyPassword:
  enable: true
  promptMessage: 请输入访问本文章的密码
  errorMessage: 密码错误，将返回主页！

# busuanzi(http://busuanzi.ibruce.info/) website statistics
# 不蒜子(http://busuanzi.ibruce.info/) 网站统计
busuanziStatistics:
  enable: true
  totalTraffic: true # 总访问量
  totalNumberOfvisitors: true # 总人次

# Add google analytics configuration
# 添加 Google Analytics 配置
googleAnalytics:
  enable: false
  id:

# The used front-end library can be replaced with the corresponding CDN address as needed,
# If the specific version is not specified below, you can use the latest version.
# 使用到的前端库，可按需替换成对应的CDN地址，如果下面未指定具体的版本号，使用最新的版本即可.
libs:
  css:
    fontAwesome: /libs/awesome/css/font-awesome.min.css # V4.7.0
    materialize: /libs/materialize/materialize.min.css # 1.0.0
    aos: /libs/aos/aos.css
    animate: /libs/animate/animate.min.css # V3.5.1
    lightgallery: /libs/lightGallery/css/lightgallery.min.css # V1.6.11
    # 由于安装了hexo-tag-aplayer, 所以不用手动引入css，js库了
    # aplayer: /libs/aplayer/APlayer.min.css
    aplayer: /assets/css/APlayer.min.css
    # 由于安装了hexo-tag-dplayer, 所以不用手动引入css，js库了
    # dplayer: /libs/dplayer/DPlayer.min.css
    dplayer: /assets/css/DPlayer.min.css
    gitalk: /libs/gitalk/gitalk.css
    jqcloud: /libs/jqcloud/jqcloud.css
    tocbot: /libs/tocbot/tocbot.css
  js:
    jquery: /libs/jquery/jquery-2.2.0.min.js
    materialize: /libs/materialize/materialize.min.js # 1.0.0
    masonry: /libs/masonry/masonry.pkgd.min.js # v4.0.0
    aos: /libs/aos/aos.js
    scrollProgress: /libs/scrollprogress/scrollProgress.min.js
    lightgallery: /libs/lightGallery/js/lightgallery-all.min.js # V1.6.11
    clicklove: /libs/others/clicklove.js
    busuanzi: /libs/others/busuanzi.pure.mini.js
    # aplayer: /libs/aplayer/APlayer.min.js
    aplayer: /assets/js/APlayer.min.js
    # dplayer: /libs/dplayer/DPlayer.min.js
    dplayer: /assets/js/DPlayer.min.js
    crypto: /libs/cryptojs/crypto-js.min.js
    echarts: /libs/echarts/echarts.min.js
    gitalk: /libs/gitalk/gitalk.min.js
    jqcloud: /libs/jqcloud/jqcloud-1.0.4.min.js
    tocbot: /libs/tocbot/tocbot.min.js

# The post featured images that needs to be displayed when there is no image.
# 无文章特色图片时需要显示的文章特色图片.
featureImages: 
- /medias/featureimages/0.jpg
- /medias/featureimages/1.jpg
- /medias/featureimages/2.jpg
- /medias/featureimages/3.jpg
- /medias/featureimages/4.jpg
- /medias/featureimages/5.jpg
- /medias/featureimages/6.jpg
- /medias/featureimages/7.jpg
- /medias/featureimages/8.jpg
- /medias/featureimages/9.jpg
- /medias/featureimages/10.jpg
- /medias/featureimages/11.jpg
- /medias/featureimages/12.jpg
- /medias/featureimages/13.jpg
- /medias/featureimages/14.jpg
- /medias/featureimages/15.jpg
- /medias/featureimages/16.jpg
- /medias/featureimages/17.jpg
- /medias/featureimages/18.jpg
- /medias/featureimages/19.jpg
- /medias/featureimages/20.jpg
- /medias/featureimages/21.jpg
- /medias/featureimages/22.jpg
- /medias/featureimages/23.jpg

  # default configs that the default policy for every articles/posts
  # default 配置文章的默认转载规则

  # you can define reprint policy for a single article in the front-matter of the specific md file using this key: reprintPolicy
  # 您可以使用在文章md文件的 front-matter 中指定 reprintPolicy 来给单个文章配置转载规则

  # 可用的转载规则有（available reprint policies are）：
  # 这些转载规则的意义请参考(you can refer to this link FMI)：https://creativecommons.org/choose/?lang=zh
  # cc_by（知识共享署名 4.0 国际许可协议 Creative Commons Attribution-NoDerivatives 4.0 International License）
  # cc_by_nd（知识共享署名-禁止演绎 4.0 国际许可协议 Creative Commons Attribution-NoDerivatives 4.0 International License）
  # cc_by_sa（知识共享署名-相同方式共享 4.0 国际许可协议 Creative Commons Attribution-ShareAlike 4.0 International License）
  # cc_by_nc（知识共享署名-非商业性使用 4.0 国际许可协议 Creative Commons Attribution-NoDerivatives 4.0 International License）
  # cc_by_nc_nd（知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议 Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License）
  # cc_by_nc_sa（知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议 Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License）

  # cc0（CC0 1.0 通用 (CC0 1.0) 公共领域贡献 CC0 1.0 Universal (CC0 1.0) Public Domain Dedication） https://creativecommons.org/publicdomain/zero/1.0/deed.zh

  # noreprint（不允许转载 not allowed to reprint）
  # pay（付费转载 pay for reprinting）
reprint:
  enable: true # whether enable reprint section 是否启用“转载规则限定模块”
  default: cc_by
