# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/


# Site
title: WillHappy
subtitle: 水火
description: Know the world, Find yourself
author: Will
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.willhappy.cn
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

# hexo渲染排除 | 路径是相对于source目录的路径
skip_render: '*.html'

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace:
# 代码高亮显示
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'tomorrow'
  line_number: false    # default false
  custom_css:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 12
pagination_dir: page

# Disqus Disqus插件，我们会替换成“多说”，不修改
#disqus_shortname:


# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#blog第一版
#theme: yelee
# theme: hexo-theme-miho
theme: hexo-theme-matery

# 搜索
search:
  path: search.xml
  field: post

# 中文链接转拼音（可选的
permalink_pinyin:
  enable: true
  separator: '-' # default: '-'

# Live2D
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: true
  debug: false
  model:
    use: live2d-widget-model-epsilon2_1
  display:
    position: left
    width: 150
    height: 300
  mobile:
    show: true
  react:
    opacity: 0.7

# hexo-tag-aplayer
aplayer:
  meting: true

# 在线联系 | DaoVoice
daovoice:
  enable: true
  app_id: ab5cf222
  user_id: willhappy   # 必填: 该用户在您系统上的唯一ID
  email: ctwang1994@163.com    # 选填:  该用户在您系统上的主邮箱
  name: 甩甩哒博主      # 选填: 用户名
  signed_up: 1449821660      # 选填: 用户的注册时间，用Unix时间戳表示

# 鼠标点击桃心效果
# 主题配置文件中配置了
# love: true

# Post wordcount display settings字数统计插件
# Dependencies: https://github.com/willin/hexo-wordcount
# 打开之后，会同时打开文章文字统计， 阅读时长和全站文字统计
# 在主题文件中配置
# wordcount:
#   enable: true
#   postWordCount: true
#   min2read: true
#   totalCount: true

# 备案号
record:
  enable: true
  value: 鲁ICP备2024094097号-1

footer:
  qrcode: 
    enable: true
    reward: http://oss.willhappy.cn/private/mm_reward_qrcode.png
    wechat: http://oss.willhappy.cn/private/qrcode_for_gzh.jpg

# Extensions
## Plugins: http://hexo.io/plugins/
#RSS订阅
plugin:
- hexo-generator-feed
#Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date

# sitemap生成插件配置
Plugins:
- hexo-generator-baidu-sitemap
- hexo-generator-sitemap

baidusitemap:
  path: baidusitemap.xml
sitemap:
  path: sitemap.xml

# 百度链接提交 | 主动推送
baidu_url_submit:
  count: 10 ## 提交最新的一个链接
  host: blog.willhappy.cn ## 在百度站长平台中注册的域名
  token: baidu_token ## 请注意这是您的秘钥，所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里

# 百度链接提交 | 自动推送
baidu_push: true


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: git
    repo: git@github.com:williamHappy/williamHappy.github.io.git
    branch: master
  - type: baidu_url_submitter
