name: HEXO CI

on:
  push:
    branches:
    - blog_source_matery

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "williamhappy"
          git config --global user.email "ctwang1994@163.com"
          # 替换同目录下的_config.yml文件中baidu_token字符串为github后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
          sed -i "s/$secrets.Baidu_Url_Submit_Token/${Baidu_Url_Submit_Token}/g" ./_config.yml
          cat ./_config.yml
      - name: Install dependencies
        run: |
          npm i node-gyp -g
          npm install nodejieba@v2.5.2 -g
          npm i -g hexo-cli
          npm i
      - name: Deploy hexo
        run: |
          hexo clean && hexo generate && hexo deploy